-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE stores (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name TEXT NOT NULL,
 slogan TEXT,
 rating DECIMAL(3,1) DEFAULT 4.9,
 business_hours TEXT,
 address TEXT,
 logo_url TEXT,
 hero_image_url TEXT,
 latitude DECIMAL(10,7),
 longitude DECIMAL(10,7),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE stores ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_stores ON stores FOR SELECT USING (true);

