-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE profiles (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 name TEXT,
 phone TEXT,
 avatar_url TEXT,
 member_level TEXT DEFAULT '普通会员',
 points INTEGER DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_profiles ON profiles FOR SELECT USING (true);
CREATE POLICY users_insert_own_profile ON profiles FOR INSERT WITH CHECK (true);

