-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE time_slots (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 staff_id UUID REFERENCES staff(id) ON DELETE CASCADE,
 service_id UUID REFERENCES services(id) ON DELETE CASCADE,
 date DATE NOT NULL,
 start_time TIME NOT NULL,
 end_time TIME NOT NULL,
 capacity INTEGER DEFAULT 1,
 booked_count INTEGER DEFAULT 0,
 is_available BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE time_slots ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_time_slots ON time_slots FOR SELECT USING (is_available = true AND booked_count < capacity);

