-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE staff_services (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 staff_id UUID REFERENCES staff(id) ON DELETE CASCADE,
 service_id UUID REFERENCES services(id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE staff_services ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_staff_services ON staff_services FOR SELECT USING (true);

