-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE staff (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name TEXT NOT NULL,
 title TEXT,
 specialties TEXT[],
 years_of_experience INTEGER,
 rating DECIMAL(3,1) DEFAULT 4.8,
 service_count INTEGER DEFAULT 0,
 keywords TEXT[],
 avatar_url TEXT,
 is_active BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE staff ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_staff ON staff FOR SELECT USING (is_active = true);

