-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE coupons (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name TEXT NOT NULL,
 type TEXT CHECK (type IN ('discount', 'times_card')),
 value DECIMAL(10,2),
 times_count INTEGER,
 expire_date DATE,
 is_active BOOLEAN DEFAULT true,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_coupons ON coupons FOR SELECT USING (is_active = true);

