-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE appointments (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 reservation_no TEXT UNIQUE NOT NULL,
 service_id UUID REFERENCES services(id) ON DELETE SET NULL,
 staff_id UUID REFERENCES staff(id) ON DELETE SET NULL,
 time_slot_id UUID REFERENCES time_slots(id) ON DELETE SET NULL,
 user_name TEXT NOT NULL,
 user_phone TEXT NOT NULL,
 guest_count INTEGER DEFAULT 1,
 notes TEXT,
 is_first_visit BOOLEAN DEFAULT true,
 wechat TEXT,
 member_no TEXT,
 status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'cancelled', 'no_show')),
 date DATE NOT NULL,
 time TIME NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_appointments ON appointments FOR SELECT USING (true);
CREATE POLICY anon_insert_appointments ON appointments FOR INSERT WITH CHECK (true);

